spring.application.name=TrailTracker
spring.datasource.url=jdbc:h2:mem:traildb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=le
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

